const types = {
  NETWORK_STATUS: {
    CONNECTING: "CONNECTING",
    CONNECTED: "CONNECTED",
    DISCONNECTED: "DISCONNECTED",
    MASTERING: "MASTERING"
  },
  CHRONO_STATUS: {
    CREATED: "CREATED",
    STARTED: "STARTED",
    STOPPED: "STOPPED"
  },
  COLLECTIONS: {
    CHRONOS: "chronos"
  },
  ERRORS: {
    CHRONO_EXPIRED: "CHRONO_EXPIRED"
  }
};

export default types;
